testomatio.batch.size=5
testomatio.batch.flush.interval=20
testomatio.url=https://app.testomat.io/
testomatio.run.title=test run title (property file)
testomatio.api.key=tstmt_pB26WHv-jCiDolD7B97qSclesIUY3yWobg1747845917