name: Publish Testomatio Java Reporter Library

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Assemble
        run: ./gradlew assemble -x test

#      - name: Tests
#        run: ./gradlew test --parallel

#      - name: Build with Gradle
#        run: ./gradlew build

#      - name: Publish to Maven Central
#        run: ./gradlew publish - parallel
#        env:
#          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
#          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
#          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
#          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}